language: python
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

dist: trusty

addons:
  apt:
    packages:
      - expect-dev # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - python-pandas

stages:
  - linting
  - test

jobs:
  include:
    - stage: linting
      name: "linting"
      env:
        - LINT_CHECK="1"

    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT="0"
          EXCLUDE="hr_worked_days_from_activity,hr_contract_security,hr_timesheet_security"

env:
  global:
    - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - sed -i 's/manifest_required_author\=.*/manifest_required_author="OpenSynergy
    Indonesia"/g' ${HOME}/maintainer-quality-tools/travis/cfg/travis_run_pylint_pr.cfg
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
